"""Fixed error messages returned by API endpoints."""

LOGIN_CREDENTIALS_REQUIRED = "User ID and password are required."
ACCOUNT_DATABASE_NOT_CONFIGURED = "Account database is not configured."
ACCOUNT_DATABASE_UNAVAILABLE = "Account database is unavailable."
INVALID_CREDENTIALS = "Invalid user ID or password."
USERNAME_INVALID = "Username must be 3–32 letters, digits, underscores, or hyphens and start with a letter."
FULL_NAME_REQUIRED = "Full name is required."
FULL_NAME_INVALID = "Full name must contain 2–120 printable characters."
PASSWORD_INVALID = "Password must contain 8–1024 characters."
USERNAME_TAKEN = "That username is already taken."
SESSION_START_FAILED = "Could not start a session. Sign in with your new account."
QUESTION_INVALID = "Question must be a non-empty string of at most 2000 characters."
ANSWER_SERVICE_UNAVAILABLE = "The answer service is unavailable. Please retry later."
AUDIT_PRIVILEGE_REQUIRED = "Audit-view privilege required."
PAYROLL_INGEST_FORBIDDEN = "Only HR Payroll may ingest payroll documents."
DOCUMENT_FIELDS_REQUIRED = "Title, content, and a valid owner are required."
DOCUMENT_INDEX_FAILED = "Document indexing failed. Please retry."
REQUEST_TOO_LARGE = "Request is too large"
JSON_OBJECT_REQUIRED = "JSON object required"
SIGN_IN_REQUIRED = "Sign in is required."
INVALID_REQUEST_ORIGIN = "Invalid request origin."
INVALID_JSON_REQUEST = "Invalid JSON request."
UNKNOWN_ENDPOINT = "Unknown endpoint."
